[project]
name = "prefect-quickstart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "prefect>=3.4.20",
]

[dependency-groups]
dev = [
    "ruff>=0.13.2",
]
